import Head from "next/head";
import { Theme, Stack } from "@mui/material";
import { makeStyles } from "@mui/styles";
import {
  useGetAllPostsQuery,
  useGetAllUsersQuery,
} from "@src/generated/graphql";
import { useDispatch } from "react-redux";
import List from "@src/components/list";
import PillList from "@src/components/pill-list";

const useStyles = makeStyles((theme: Theme) => ({
  app: {
    backgroundColor: theme.palette.background.default,
  },
  list: {
    backgroundColor: theme.palette.common.white,
    p: 2,
  },
}));

export default function Home() {
  const classes = useStyles();
  const dispatch = useDispatch();
  const { data: usersData, isLoading: isUsersDataLoading } =
    useGetAllUsersQuery();
  const { data: postsData, isLoading: isPostDataLoading } =
    useGetAllPostsQuery();

  return (
    <Stack
      className={classes.app}
      width="100vw"
      height="100vh"
      alignItems="center"
      justifyContent="center"
    >
      <Head>
        <title>Charisma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack direction="row" spacing="50px">
        <List
          items={usersData?.users?.data ?? []}
          formatItem={(user) => ({
            id: user.id,
            title: user.name,
            subTitle: user.email,
          })}
        />
        <List
          items={postsData?.posts?.data ?? []}
          formatItem={(post) => ({
            id: post.id,
            title: post.title,
            subTitle: post.body,
          })}
        />
        <PillList />
      </Stack>
    </Stack>
  );
}
