import Head from "next/head";
import { Theme, Stack, TextField } from "@mui/material";
import { makeStyles } from "@mui/styles";
import { useGetAllUsersQuery } from "@src/generated/graphql";
import en from "@src/lang/en";

const useStyles = makeStyles((theme: Theme) => ({
  app: {
    backgroundColor: theme.palette.background.default, 
  }, 
  list: {
    backgroundColor: theme.palette.common.white,
    p: 2,
  },
}));

export default function Home() {
  const classes = useStyles();
  const { data } = useGetAllUsersQuery();

  console.log(data);

  return (
    <Stack
      className={classes.app}
      width="100vw"
      height="100vh"
      alignItems="center"
      justifyContent="center"
    >
      <Head>
        <title>Charisma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack direction="row" spacing="50px">
        <Stack className={classes.list} width="400px" height="725px" p={2}>
          <TextField placeholder={en.SEARCH} variant="outlined" />
        </Stack>
        <Stack className={classes.list} width="400px" height="725px" p={2}>
          <TextField placeholder={en.SEARCH} variant="outlined" />
        </Stack>
        <Stack className={classes.list} width="400px" height="725px" p={2}>
          d
        </Stack>
      </Stack>
    </Stack>
  );
}
